更新了项目规划。
CUCCS/ns pull request #50
Opened 2017-09-19 15:35 UTC by CUCfromHY001

2017-09-19 22:39 UTC, c4pr1c3 commented on 2017-2/MlCjh/项目规划beta0_2.md
> +# 需求分析
一个合格的需求分析最基本的要求就是能给出**具体化**、**定量化**、**可验收**的功能点和指标描述，而不是堆砌一些**含糊其辞**的形容词。

* 多强是**较强**？
* **分析**和**整合**能力具体表现形式是什么？
* **良好**的UI设计如何定义和理解？

现在是定计划阶段，如果你都已经把**需求分析**给完全写出来了，那不就等于完成了这个阶段的任务了吗？事实上，你还没有正式开始做需求分析，甚至还没有开始如何撰写一个**合格**的需求分析。所以，这个阶段的工作本身也是计划的一部分，应该留给需求分析一段具体时间，比如我上课时候提示所有人的：在月底前完成计划，实际上就是暗含了只有对需求理解清楚，定义明晰了之后，计划方案才知道要做哪些具体研发工作，才有具体的研发目标。月底前提交的计划方案，首先要做好的就是**需求分析**。

2017-09-19 22:39 UTC, c4pr1c3 commented on 2017-2/MlCjh/项目规划beta0_2.md
> +  * 1、首先确定数据的来源。(计划选取一些知名资讯网站作为数据来源)
* **知名**资讯网站的选取标准是什么？现在不能确定出一个具体的计划名单吗？
* 数据预处理就是**建立正则表达式**吗？

其他建议和意见，请参考我给你们项目的另一组有缘人的评审意见：https://github.com/CUCCS/ns/pull/49

2017-10-10 10:49 UTC, kadaokaduan approved these changes
实验完成较为认真，且实验目标达成。

2017-10-18 12:41 UTC, c4pr1c3 requested changes
实验报告，没有放在自己的目录下，直接放在了 ``2017-2/翻转课堂/`` 下面，这样是被禁止的。你自己有个人目录 ``2017-2/MlCjh/`` 期望的应该是 ``2017-2/MlCjh/翻转课堂/01/``

2018-01-23 15:48 UTC, closed without merging