翻转课堂_01
CUCCS/ns pull request #53
Opened 2017-09-28 08:23 UTC by BurnyMcDull

翻转课堂实验1 采取ppt方式进行汇报

2017-10-05 14:06 UTC, c4pr1c3 requested changes
如果能配上一个你自己绘制的简单网络拓扑图来说明3台VM的联网方式和每个网卡接口的配置信息就更好了

2017-10-05 14:06 UTC, c4pr1c3 commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +内部网络地址：192.168.56.101
图文不符，你的配图里是`192.168.26.2`，且配图没有体现DNS地址

2017-10-05 14:06 UTC, c4pr1c3 commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +#### Kali: 网关拥有两个网卡 一个内部网络网卡 一个NAT网卡
联网方式到底是`NAT`还是`NAT网络`？Virtualbox里没有`NAT网卡`这种联网方式

2017-10-05 14:06 UTC, c4pr1c3 commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +![image](https://github.com/BurnyMcDull/ns/raw/master/2017-2/Szy_HW1/5.png)
`Ctrl-Z`不是用来中止程序执行，只是把程序放到了`后台`执行，后续还可以通过`fg`把后台程序拉回前台继续执行。

`Ctrl-C`才是用来中止程序执行的快捷键。

2017-10-05 14:06 UTC, c4pr1c3 commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +![image](https://github.com/songyawen/ns/raw/master/2017-2/Sonya_Coursework/FlippedClassroom_HW/HW_1/6.png)
图文不符，你的配图是`192.168.26.2`，DNS服务器地址并没有在截图中体现出来。

2017-10-05 14:06 UTC, c4pr1c3 commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +#### Kali: 网关拥有两个网卡 一个内部网络网卡 一个NAT网卡
对于Virtualbox来说，没有所谓的`NAT网卡`，只有`NAT`和`NAT网络`两种联网方式，你到底用的是哪一种呢？

2017-10-06 14:56 UTC, BurnyMcDull commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +#### Kali: 网关拥有两个网卡 一个内部网络网卡 一个NAT网卡
使用的是NAT网络

2017-10-06 14:56 UTC, BurnyMcDull commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +#### Kali: 网关拥有两个网卡 一个内部网络网卡 一个NAT网卡
使用的是NAT网络

2017-10-06 15:02 UTC, BurnyMcDull commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +![image](https://github.com/songyawen/ns/raw/master/2017-2/Sonya_Coursework/FlippedClassroom_HW/HW_1/6.png)
老师抱歉 这里是我自己的失误 我下面的所有图片都上传github里面了 这里是我格式按照同学的复制的 下方图片都进行更改了 这里忘记了 我稍后就进行修改

2017-10-16 11:18 UTC, BurnyMcDull commented on 2017-2/Szy_HW1/翻转课堂实验1.md
> +内部网络地址：192.168.56.101
老师抱歉 这里是我的问题，我在修改图片路径时出现错误，导致第一个路径是复制的 没有进行修改

2017-11-12 07:12 UTC, c4pr1c3 approved these changes

2017-11-12 07:13 UTC, c4pr1c3 commented
今年所有人的作业都不再合并到作业仓库，每次作业批改完毕后，我会统一关闭每个PR，助教会记录大家的评分。同时，避免其他人在发送PR前还需要先更新作业仓库里的新提交文件，减少下载时间，提高提交PR的效率。

2017-11-12 07:13 UTC, closed without merging