RachelLyy-Lab1
CUCCS/ns pull request #58
Opened 2017-09-28 16:27 UTC by RachelLYY

2017-10-03 06:53 UTC, c4pr1c3 commented on 2017-2/大作业计划表.md
> +  * [利用阿里云的API实现动态域名解析](http://blog.csdn.net/jiyuxian/article/details/53762646)
本题的设计背景来自清华大学段海新教授在2015年阿里云安全峰会上的一次演讲：[《网络空间的信任模型:现状与挑战之——DNS信任体系》](https://wenku.baidu.com/view/376a4d72551810a6f52486f9.html)，具体来说，你应该关注的是这个PPT中的“DNS信任体系的攻击面之三: 控制解析路径/链路”，对照PPT中的内容，你设计和完成的这个系统应该能证明：

* 智利用户访问facebook.com的域名解析 可能经过中国
* .CN 的域名解析可能会依赖于中国以外的DNS解析服务器
* 域名空间中，国家的边界十分模糊。即使是一个国际的顶级域名解析，也可能会依赖于地处于其他国家的域名解析服务器

2017-10-03 06:53 UTC, c4pr1c3 commented on 2017-2/大作业计划表.md
> +* R语言绘图
除非你很熟悉R语言，否则，不建议你使用一门全新的语言来完成这里的绘图任务。我的建议是整个系统应该实现成网页形式，前端负责解析过程的可视化（包括地图底图绘制、解析涉及到的IP对应的地理位置归属地信息等），后端负责域名和IP解析过程实现、IP归属地信息查询、域名解析服务器归属地信息查询等。

2017-10-11 05:46 UTC, kadaokaduan requested changes
* 实验报告撰写较为规范、严谨，但个别markdown语法的使用有问题，请自查
* 一个共性的问题请参见 #69

2017-10-11 05:46 UTC, kadaokaduan commented on 2017-2/Lab1/chap0x01 基于VirtualBox的网络攻防基础环境搭建实例讲解.md
> +   配置内网连通外网时，是否只需配置虚拟机中能连接外网的网卡转发内网ip即可。
是的，你的作业也实现了这一点

2017-11-16 14:01 UTC, closed without merging