翻转课堂实验1+大作业任务列表
CUCCS/ns pull request #60
Opened 2017-09-29 03:03 UTC by ghan3

2017-10-05 07:27 UTC, kadaokaduan requested changes
作业总体来说完成质量较高，但仍旧有一些细节性问题，可进行完善

2017-10-05 07:27 UTC, kadaokaduan commented on 2017-2/FlippedClassroomHW1/HW1.md
> +* 解决网关上网的问题。因为网关可以通过外网网卡上网，所以内网网卡将数据包发给外网网卡，从而解决网关的上网问题，具体操作如下所示，参考链接：https://linux.cn/article-5595-1.html 。
具体**端口转发**的相应指令应给出

2017-10-05 07:27 UTC, kadaokaduan commented on 2017-2/FlippedClassroomHW1/HW1.md
> + 上面的命令是阻止IP为10.0.2.5的机器访问靶机。
既然靶机在内网中，则理应无法被攻击机访问。防火墙规则设置有必要吗？

2017-10-13 02:25 UTC, ghan3 commented on 2017-2/FlippedClassroomHW1/HW1.md
> +* 解决网关上网的问题。因为网关可以通过外网网卡上网，所以内网网卡将数据包发给外网网卡，从而解决网关的上网问题，具体操作如下所示，参考链接：https://linux.cn/article-5595-1.html 。
后面的启用IPv4转发、配置iptables防火墙、配置NAT是配置端口转发的过程，里面有具体的命令。

2017-10-13 02:29 UTC, ghan3 commented on 2017-2/FlippedClassroomHW1/HW1.md
> + 上面的命令是阻止IP为10.0.2.5的机器访问靶机。
在最初攻击机是无法访问靶机的，但是通过端口转发的方式使靶机能够上网后，攻击机就可以访问靶机了，因此添加了防火墙规则。要去掉防火墙规则并更改靶机上网方式吗？

2017-11-12 07:38 UTC, c4pr1c3 commented
今年所有人的作业都不再合并到作业仓库，每次作业批改完毕后，我会统一关闭每个PR，助教会记录大家的评分。同时，避免其他人在发送PR前还需要先更新作业仓库里的新提交文件，减少下载时间，提高提交PR的效率。

2017-11-12 07:38 UTC, closed without merging