基于VirtualBox的网络攻防基础环境搭建
CUCCS/ns pull request #63
Opened 2017-09-29 06:54 UTC by ddddyouo

2017-10-05 06:32 UTC, kadaokaduan requested changes
- 从你的实验报告来看，完成较为认真，一些细节问题应更加注意
- 一些共性问题请参考[issue #69](https://github.com/CUCCS/ns/issues/69)

2017-10-05 06:32 UTC, kadaokaduan commented on 2017-2/基于VirtualBox的网络攻防基础环境搭建.md
> +#####	（图片因为我调了尺寸变得很糊，不知道怎么解决。不是网上找的图片！）
- 相信你了~~~你可以将图片同样上传到本仓库。
- 另外，猜测这种情况可能会因为你使用了微信截图工具，请尝试使用系统截图工具。

2017-10-05 06:32 UTC, kadaokaduan commented on 2017-2/基于VirtualBox的网络攻防基础环境搭建.md
> +	*	靶机、攻击者主机、网管之间的网络使用Host-Only网卡
**网管**，再充十块钱？？

2017-11-12 07:42 UTC, c4pr1c3 commented
今年所有人的作业都不再合并到作业仓库，每次作业批改完毕后，我会统一关闭每个PR，助教会记录大家的评分。同时，避免其他人在发送PR前还需要先更新作业仓库里的新提交文件，减少下载时间，提高提交PR的效率。

2017-11-12 07:42 UTC, closed without merging