翻转课堂实验报告
CUCCS/ns pull request #70
Opened 2017-10-08 09:52 UTC by Anna-YJ

2017-10-10 11:02 UTC, Raztyn requested changes

2017-10-10 11:02 UTC, Raztyn commented on 2017-2/YJe_NS/HOMEWORK-FlippedClassroom/Homework_01/HW_01.md
> +本次实验在听取了老师和同学的讲解后重新做过，思路如上拓扑图，在处理网关两块网卡不能上网时，参考了此链接：https://linux.cn/article-5595-1.html， 设置用IP转发使内部网络（internal）连接到互联网，将内部网络的包转发到NAT的那个网络，此时两张网卡同时打开也能上网。按照这条路，靶机应当能上网，且能访问攻击机，但此时却不行。（查看路由，默认路由设置没问题），
* Nice attitude！如果能多一些文字描述具体工作就更好了 :)
* 不能实现上外网的原因可能是因为没有开启ip_forward,可以看一下ip_forward设置。

2017-10-13 01:36 UTC, Anna-YJ commented on 2017-2/YJe_NS/HOMEWORK-FlippedClassroom/Homework_01/HW_01.md
> +本次实验在听取了老师和同学的讲解后重新做过，思路如上拓扑图，在处理网关两块网卡不能上网时，参考了此链接：https://linux.cn/article-5595-1.html， 设置用IP转发使内部网络（internal）连接到互联网，将内部网络的包转发到NAT的那个网络，此时两张网卡同时打开也能上网。按照这条路，靶机应当能上网，且能访问攻击机，但此时却不行。（查看路由，默认路由设置没问题），
好的，ip_forward已经开启，在机房测试没有问题~自己的笔记本上的问题还在找~

2017-10-13 03:19 UTC, Anna-YJ commented
好哒，核查过后，会提交更新后的实验报告~

2017-11-16 14:00 UTC, closed without merging