基于virtualbox网络攻防环境搭建
CUCCS/ns pull request #71
Opened 2017-10-08 13:40 UTC by xuyanqin

2017-10-10 11:56 UTC, Raztyn commented on 2017-2/xyq/NSLab-report/网络安全实验一.md
> +
实验通过，没有问题，下次可以多加一些文字描述具体工作。

2017-10-10 12:00 UTC, Raztyn approved these changes
实验通过，没有问题，加上网络拓扑图就更好了，下次可以多加一些文字描述具体工作。大作业计划不属于实验报告，建议下次使用不同分支提交。

2017-10-18 12:30 UTC, c4pr1c3 requested changes
@Raztyn 你的批改有错误，注意查看我的批注回复。

2017-10-18 12:30 UTC, c4pr1c3 commented on 2017-2/xyq/NSLab-report/网络安全实验一.md
> +![](https://i.imgur.com/85t7Btl.png)
靶机的DNS为什么设置为8.8.8.8？对于本次实验来说，虽然没有问题，可以满足实验要求。但，后续在红蓝对抗时，这个DNS应该配置为靶机所在网络的网关IP，由自己搭建的DNS转发服务器来提供DNS解析服务会更有利于入侵检测的实现。

2017-10-18 12:30 UTC, c4pr1c3 commented on 2017-2/xyq/NSLab-report/网络安全实验一.md
> +![](https://i.imgur.com/08aKSb9.png)
错别字：是 --> 使

2017-10-18 12:30 UTC, c4pr1c3 commented on 2017-2/xyq/NSLab-report/网络安全实验一.md
> +![](https://i.imgur.com/08aKSb9.png)
更重要的是，你这里的防火墙配置第一多余，第二会导致后续的红蓝对抗实验中，靶机无法成功被攻击者主机远程控制：因为攻击者主机到靶机的下行数据会被网关drop掉。

2017-10-18 12:30 UTC, c4pr1c3 commented on 2017-2/xyq/NSLab-report/网络安全实验一.md
> + ![](https://i.imgur.com/hSIeZx0.png)
配图并不能证明是在靶机上执行的ping

2017-10-18 12:30 UTC, c4pr1c3 commented on 2017-2/xyq/NSLab-report/网络安全实验一.md
> + ![](https://i.imgur.com/wYABDQz.png)
这里图中的192.168.1.4是从哪儿来的？我有理由怀疑你这里的配图和你前述的实验配置并不匹配。

2017-10-18 12:30 UTC, c4pr1c3 commented on 2017-2/xyq/NSLab-report/网络安全实验一.md
> +![](https://i.imgur.com/aA8Iudr.png)
如果你前述确实配置了iptables拒绝了来自10.0.2.2的入站数据，那么你这里在网关上应该是ping不通攻击者主机的。

2017-11-12 07:54 UTC, c4pr1c3 commented
今年所有人的作业都不再合并到作业仓库，每次作业批改完毕后，我会统一关闭每个PR，助教会记录大家的评分。同时，避免其他人在发送PR前还需要先更新作业仓库里的新提交文件，减少下载时间，提高提交PR的效率。

2017-11-12 07:54 UTC, c4pr1c3 commented
今年所有人的作业都不再合并到作业仓库，每次作业批改完毕后，我会统一关闭每个PR，助教会记录大家的评分。同时，避免其他人在发送PR前还需要先更新作业仓库里的新提交文件，减少下载时间，提高提交PR的效率。

2017-11-12 07:54 UTC, c4pr1c3 commented
今年所有人的作业都不再合并到作业仓库，每次作业批改完毕后，我会统一关闭每个PR，助教会记录大家的评分。同时，避免其他人在发送PR前还需要先更新作业仓库里的新提交文件，减少下载时间，提高提交PR的效率。

2017-11-12 07:54 UTC, closed without merging