基于virtualbox的网络攻防环境搭建
CUCCS/ns pull request #72
Opened 2017-10-08 14:12 UTC by tyushua1

2017-10-10 12:15 UTC, Raztyn commented on 2017-2/ys/基于virtualbox的网络攻防环境搭建.md
> +  ![](https://i.imgur.com/qWIyD4e.png)
没有看见你在网关处给靶机设置ip转发规则，这也可能是后面靶机无法访问外网的原因。

2017-10-10 12:21 UTC, Raztyn commented on 2017-2/ys/基于virtualbox的网络攻防环境搭建.md
> +  ![](https://i.imgur.com/0ulhkXR.png)
这里不需要给靶机的防火墙设置规则，攻击主机就应该无法访问靶机。

2017-10-10 12:21 UTC, Raztyn commented on 2017-2/ys/基于virtualbox的网络攻防环境搭建.md
> + ![](https://i.imgur.com/jntJq8K.png)
这里只能看见靶机节点制作成了基础镜像。

2017-10-10 12:24 UTC, Raztyn commented on 2017-2/ys/基于virtualbox的网络攻防环境搭建.md
> +  ![](https://i.imgur.com/qWIyD4e.png)
这里没有看见你在网关设置靶机的ip转发规则，这也可能是后面靶机不能访问互联网的原因。

2017-10-10 12:26 UTC, Raztyn commented on 2017-2/ys/基于virtualbox的网络攻防环境搭建.md
> +  ![](https://i.imgur.com/0ulhkXR.png)
这里不需要给靶机设置防火墙规则，请看
* #69

2017-10-10 12:27 UTC, Raztyn requested changes
* 如果加上网络拓扑图就更好了

2017-11-12 07:57 UTC, c4pr1c3 commented
今年所有人的作业都不再合并到作业仓库，每次作业批改完毕后，我会统一关闭每个PR，助教会记录大家的评分。同时，避免其他人在发送PR前还需要先更新作业仓库里的新提交文件，减少下载时间，提高提交PR的效率。

2017-11-12 07:57 UTC, closed without merging