Final assignment
CUCCS/ns pull request #82
Opened 2017-10-29 06:12 UTC by wq0712

2017-11-29 04:59 UTC, c4pr1c3 requested changes
1. markdown语法依然没有按照 https://github.com/CUCCS/ns/issues/77 书写
2. 大作业、调研报告缺少必要的参考文献引用标注，且直接复制粘贴的文字较多，没有做必要的引用标注（特殊格式说明这是一段直接复制粘贴的文字）

2017-11-29 04:59 UTC, c4pr1c3 commented on 2017-2/Final assignment_ly_wq/域名管理机制_wq.md
> +>域名由若干英文单词组成，中间由“·”分隔，从右到左依次为顶级域名段、次高域名段等。
引用他人数据、观点和资料要给出引用出处： http://www.newsjz.com/wxqgr/Article/UploadFiles/201609/2016092314265531.ppt

抛开 ``sina.com.cn`` 这个具体例子来看，``com：网络名,也叫二级域名， 代表部门系统或隶属一级区域的下级机构。`` 这个认知是错误的。

2017-11-29 04:59 UTC, c4pr1c3 commented on 2017-2/Final assignment_ly_wq/域名管理机制_wq.md
> +>国家顶级域名（iTLD）：cn、us、uk
ccTLDs, country code top-level domain，国家顶级域名

2017-12-22 06:12 UTC, wq0712 commented
从SQL注入到shell

2018-01-23 15:48 UTC, closed without merging