翻转课堂分支
CUCCS/ns pull request #86
Opened 2017-10-31 12:44 UTC by choitop

2017-11-03 08:38 UTC, choitop commented
端口转发

2017-11-16 12:43 UTC, Raztyn requested changes

2017-11-16 12:43 UTC, Raztyn commented on 2017-2/LAB_whx/LAB1/基于VBOX的网络攻防基础环境搭建.md
> +![多重加载](images/17.png)
截图应该加入虚拟机名称

2017-11-16 12:43 UTC, Raztyn commented on 2017-2/LAB_whx/LAB2/实验报告.md
> +68端口无法打开
参见 #95 UDP scan实验的评论

2017-11-16 14:00 UTC, closed without merging